#!/bin/bash
# Script para visualizar conteúdo dos arquivos .lua

echo "======================================"
echo "📂 ARQUIVOS DISPONÍVEIS"
echo "======================================"
echo ""
echo "Servidor:"
echo "  1) ServerMain.lua"
echo "  2) CheckpointService.lua"
echo "  3) StarCollectionService.lua"
echo "  4) PowerUpService.lua"
echo ""
echo "Cliente:"
echo "  5) ClientMain.lua"
echo "  6) MainUI.lua"
echo ""
echo "Compartilhado:"
echo "  7) GameConfig.lua"
echo "  8) PlayerData.lua"
echo ""
echo "======================================"
echo "Para ver o conteúdo de um arquivo:"
echo "  cat src/server/ServerMain.lua"
echo "  cat src/client/ClientMain.lua"
echo "  etc..."
echo "======================================"
